config/routes.rb
Rails.application.routes.draw do
  get 'sales/new'
  post 'sales', to: 'sales#create'
  get 'sales/done', to: 'sales#done'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/sale.rb
class Sale < ApplicationRecord
  validates :cod, uniqueness: true
  validates :detail, presence: true
  validates :category, inclusion: { in: [1, 2, 3, 4, 5]}
  validates_numericality_of :value, greater_than_or_equal_to: 0, only_integer: true
  validates_numericality_of :discount, less_than_or_equal_to: 40, greater_than_or_equal_to: 0, only_integer: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  def new
    @sale = Sale.new
  end

  def create
    sale = Sale.new(sale_params)
    prepare_sale(sale)
    redirect_to sales_done_path
  end

  def done
    @sale = Sale.all.last
  end

private
def sale_params
  params.require(:sale).permit(:detail, :category, :value, :discount, :tax)
end

def prepare_sale(sale)
  sale.cod = Random.rand(10...100000)
  sale.value = (sale_params[:value].to_i) * (100 - sale_params[:discount].to_i)
  if sale_params[:tax].to_i == 0
    sale.total = sale.value * 1.19
    sale.tax = 19
  else
    sale.tax = 0
    sale.total = sale.value
  end
    # byebug
   sale.save
 end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RegistroVentas</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/sales/done.html.erb
<p> El registro fue almacenado con éxito </p>

<table>
  <tr>
    <th> ID </th>
    <th> DETALLE DE LA VENTA </th>
    <th> COD </th>
    <th> CATEGORÍA </th>
    <th> VALOR </th>
    <th> DESCUENTO </th>
    <th> IVA </th>
  </tr>

  <tr>
    <th> <%= @sale.id %> </th>
    <th> <%= @sale.detail %> </th>
    <th> <%= @sale.cod %> </th>
    <th> <%= @sale.category %> </th>
    <th> <%= @sale.value %> </th>
    <th> <%= @sale.discount %> </th>
    <th> <%= @sale.tax %></th>
  </tr>
</table>

<%= link_to "Volver", sales_new_path %>

app/views/sales/new.html.erb
<h1> Formulario de registro de ventas </h1>

<%= form_with model: Sale.new, url: sales_path, local: true, method: 'post' do |f| %>

  <%= f.label :detail, "Detalle de la venta" %>
  <%= f.text_area :detail %>

  <%= f.label :category, "Categoría" %>
  <%= f.text_field :category %>

  <%= f.label :value, "Valor" %>
  <%= f.number_field :value %>

  <%= f.label :discount, "Descuento" %>
  <%= f.number_field :discount %>

  <%= f.label :tax, "Exento de IVA" %>
  <%= f.check_box :tax %>

  <%= f.submit "Enviar" %>

  <% end %>